### ISSUE TITLE
File path written from the root

### ISSUE THREAD

**Issue by Hugo-L3174** [stack-of-tasks/sot-pattern-generator#25]
https://github.com/stack-of-tasks/sot-pattern-generator/blob/bfd3a805a26a2726d542d826b0e9563dabdde99d/tests/main.cc#L11
https://github.com/stack-of-tasks/sot-pattern-generator/blob/bfd3a805a26a2726d542d826b0e9563dabdde99d/tests/main.cc#L13

Those two lines write the direct path to the file which is an issue when the sot is not installed in /opt/openrobots

**Comment by nim65s** [comment]
Thanks for the report. I'll provide a fix for this, and you will be able to apply that if you ever found this kind of errors in other places.
